language: perl

sudo: false

perl:
    - "5.14"

addons:
    apt:
        packages:
            - libstdc++6
            - liblzma5
            - libbz2-1.0

install:
    - "cpanm --quiet --notest Bio::Perl Time::Piece File::Slurp List::Util File::Copy File::Spec"
    - "export PATH=$PWD/bin:$PATH"

script:
    - "ldd $PWD/binaries/linux/freebayes"
    - "ldd $PWD/binaries/linux/vcfuniq"
    - "ldd $PWD/binaries/linux/samtools"
    - "ldd $PWD/binaries/linux/bcftools"
    - "snippy --version"
    - "snippy --help"
    - "snippy --check"
    - "snippy --citation"
    - "! snippy --doesnotexist"
