language: perl

sudo: false

perl:
    - "5.26"

addons:
    apt:
        packages:
            - libstdc++6
            - liblzma5
            - libbz2-1.0
            - emboss
            - curl

install:
    - "cpanm --quiet --notest Bio::Perl"
    - "curl https://downloads.sourceforge.net/project/samtools/samtools/1.0/samtools-bcftools-htslib-1.0_x64-linux.tar.bz2 | tar xf -"
    - "ln -s $PWD/samtools-bcftools-htslib-1.0_x64-linux/bin/wgsim $PWD/bin/wgsim"
    - "export PATH=$PWD/bin:$PATH"

script:
    - "! (ldd $PWD/binaries/linux/freebayes | grep 'not found')"
    - "! (ldd $PWD/binaries/linux/vcfuniq   | grep 'not found')"
    - "! (ldd $PWD/binaries/linux/samtools  | grep 'not found')"
    - "! (ldd $PWD/binaries/linux/bcftools  | grep 'not found')"
    - "snippy --version"
    - "! snippy --doesnotexist"
    - "snippy --help"
    - "snippy --check"
    - "make -C test"

