language: perl

sudo: false

perl:
    - "5.26"

addons:
    apt:
        packages:
            - libstdc++6
            - liblzma5
            - libbz2-1.0
            - samtools
            - emboss

install:
    - "cpanm --quiet --notest Bio::Perl"
    - "export PATH=$PWD/bin:$PATH"
    - "ln -s $PWD/binaries/linux/samtools $PWD/bin/samtools"

script:
    - "! (ldd $PWD/binaries/linux/freebayes | grep 'not found')"
    - "! (ldd $PWD/binaries/linux/vcfuniq   | grep 'not found')"
    - "! (ldd $PWD/binaries/linux/samtools  | grep 'not found')"
    - "! (ldd $PWD/binaries/linux/bcftools  | grep 'not found')"
    - "snippy --version"
    - "! snippy --doesnotexist"
    - "snippy --help"
    - "snippy --check"
    - "make -C test"

