language: generic

addons:
    apt:
        packages:
            - libstdc++6
            - liblzma5
            - libbz2-1.0
            - bioperl

install:
    - "export PATH=$PWD/bin:$PWD/binaries/noarch:$PWD/binaries/linux:$PATH"

script:
    - "! (ldd $PWD/binaries/linux/freebayes | grep 'not found')"
    - "! (ldd $PWD/binaries/linux/vcfuniq   | grep 'not found')"
    - "! (ldd $PWD/binaries/linux/samtools  | grep 'not found')"
    - "! (ldd $PWD/binaries/linux/bcftools  | grep 'not found')"
    - "snippy --version"
    - "snippy --check"
    - "snippy-core --version"
    - "snippy-core --check"
    - "make -C test"
